import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";

const switzer = localFont({
  src: [
    {
      path: "../assets/font/Switzer-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/font/Switzer-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/font/Switzer-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/font/Switzer-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/font/Switzer-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "GreenRoad Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={switzer.className}>
        <Header />
        <main className="min-h-[200vh]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
